// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/invitation"
	"github.com/looplj/axonhub/internal/ent/project"
)

// InvitationCreate is the builder for creating a Invitation entity.
type InvitationCreate struct {
	config
	mutation *InvitationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvitationCreate) SetCreatedAt(v time.Time) *InvitationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableCreatedAt(v *time.Time) *InvitationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvitationCreate) SetUpdatedAt(v time.Time) *InvitationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableUpdatedAt(v *time.Time) *InvitationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *InvitationCreate) SetDeletedAt(v int) *InvitationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableDeletedAt(v *int) *InvitationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *InvitationCreate) SetTokenHash(v string) *InvitationCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *InvitationCreate) SetProjectID(v int) *InvitationCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *InvitationCreate) SetRoleID(v int) *InvitationCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableRoleID(v *int) *InvitationCreate {
	if v != nil {
		_c.SetRoleID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *InvitationCreate) SetExpiresAt(v time.Time) *InvitationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableExpiresAt(v *time.Time) *InvitationCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetMaxUses sets the "max_uses" field.
func (_c *InvitationCreate) SetMaxUses(v int) *InvitationCreate {
	_c.mutation.SetMaxUses(v)
	return _c
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableMaxUses(v *int) *InvitationCreate {
	if v != nil {
		_c.SetMaxUses(*v)
	}
	return _c
}

// SetUsedCount sets the "used_count" field.
func (_c *InvitationCreate) SetUsedCount(v int) *InvitationCreate {
	_c.mutation.SetUsedCount(v)
	return _c
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableUsedCount(v *int) *InvitationCreate {
	if v != nil {
		_c.SetUsedCount(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *InvitationCreate) SetProject(v *Project) *InvitationCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the InvitationMutation object of the builder.
func (_c *InvitationCreate) Mutation() *InvitationMutation {
	return _c.mutation
}

// Save creates the Invitation in the database.
func (_c *InvitationCreate) Save(ctx context.Context) (*Invitation, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvitationCreate) SaveX(ctx context.Context) *Invitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvitationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvitationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvitationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if invitation.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized invitation.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := invitation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if invitation.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized invitation.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := invitation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := invitation.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		v := invitation.DefaultMaxUses
		_c.mutation.SetMaxUses(v)
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		v := invitation.DefaultUsedCount
		_c.mutation.SetUsedCount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvitationCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Invitation.deleted_at"`)}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "Invitation.token_hash"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Invitation.project_id"`)}
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		return &ValidationError{Name: "max_uses", err: errors.New(`ent: missing required field "Invitation.max_uses"`)}
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		return &ValidationError{Name: "used_count", err: errors.New(`ent: missing required field "Invitation.used_count"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Invitation.project"`)}
	}
	return nil
}

func (_c *InvitationCreate) sqlSave(ctx context.Context) (*Invitation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvitationCreate) createSpec() (*Invitation, *sqlgraph.CreateSpec) {
	var (
		_node = &Invitation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invitation.Table, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invitation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invitation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(invitation.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(invitation.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.RoleID(); ok {
		_spec.SetField(invitation.FieldRoleID, field.TypeInt, value)
		_node.RoleID = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(invitation.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.MaxUses(); ok {
		_spec.SetField(invitation.FieldMaxUses, field.TypeInt, value)
		_node.MaxUses = value
	}
	if value, ok := _c.mutation.UsedCount(); ok {
		_spec.SetField(invitation.FieldUsedCount, field.TypeInt, value)
		_node.UsedCount = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.ProjectTable,
			Columns: []string{invitation.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invitation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvitationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvitationCreate) OnConflict(opts ...sql.ConflictOption) *InvitationUpsertOne {
	_c.conflict = opts
	return &InvitationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvitationCreate) OnConflictColumns(columns ...string) *InvitationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvitationUpsertOne{
		create: _c,
	}
}

type (
	// InvitationUpsertOne is the builder for "upsert"-ing
	//  one Invitation node.
	InvitationUpsertOne struct {
		create *InvitationCreate
	}

	// InvitationUpsert is the "OnConflict" setter.
	InvitationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *InvitationUpsert) SetUpdatedAt(v time.Time) *InvitationUpsert {
	u.Set(invitation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateUpdatedAt() *InvitationUpsert {
	u.SetExcluded(invitation.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *InvitationUpsert) SetDeletedAt(v int) *InvitationUpsert {
	u.Set(invitation.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateDeletedAt() *InvitationUpsert {
	u.SetExcluded(invitation.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *InvitationUpsert) AddDeletedAt(v int) *InvitationUpsert {
	u.Add(invitation.FieldDeletedAt, v)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *InvitationUpsert) SetTokenHash(v string) *InvitationUpsert {
	u.Set(invitation.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateTokenHash() *InvitationUpsert {
	u.SetExcluded(invitation.FieldTokenHash)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *InvitationUpsert) SetProjectID(v int) *InvitationUpsert {
	u.Set(invitation.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateProjectID() *InvitationUpsert {
	u.SetExcluded(invitation.FieldProjectID)
	return u
}

// SetRoleID sets the "role_id" field.
func (u *InvitationUpsert) SetRoleID(v int) *InvitationUpsert {
	u.Set(invitation.FieldRoleID, v)
	return u
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateRoleID() *InvitationUpsert {
	u.SetExcluded(invitation.FieldRoleID)
	return u
}

// AddRoleID adds v to the "role_id" field.
func (u *InvitationUpsert) AddRoleID(v int) *InvitationUpsert {
	u.Add(invitation.FieldRoleID, v)
	return u
}

// ClearRoleID clears the value of the "role_id" field.
func (u *InvitationUpsert) ClearRoleID() *InvitationUpsert {
	u.SetNull(invitation.FieldRoleID)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *InvitationUpsert) SetExpiresAt(v time.Time) *InvitationUpsert {
	u.Set(invitation.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateExpiresAt() *InvitationUpsert {
	u.SetExcluded(invitation.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *InvitationUpsert) ClearExpiresAt() *InvitationUpsert {
	u.SetNull(invitation.FieldExpiresAt)
	return u
}

// SetMaxUses sets the "max_uses" field.
func (u *InvitationUpsert) SetMaxUses(v int) *InvitationUpsert {
	u.Set(invitation.FieldMaxUses, v)
	return u
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateMaxUses() *InvitationUpsert {
	u.SetExcluded(invitation.FieldMaxUses)
	return u
}

// AddMaxUses adds v to the "max_uses" field.
func (u *InvitationUpsert) AddMaxUses(v int) *InvitationUpsert {
	u.Add(invitation.FieldMaxUses, v)
	return u
}

// SetUsedCount sets the "used_count" field.
func (u *InvitationUpsert) SetUsedCount(v int) *InvitationUpsert {
	u.Set(invitation.FieldUsedCount, v)
	return u
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateUsedCount() *InvitationUpsert {
	u.SetExcluded(invitation.FieldUsedCount)
	return u
}

// AddUsedCount adds v to the "used_count" field.
func (u *InvitationUpsert) AddUsedCount(v int) *InvitationUpsert {
	u.Add(invitation.FieldUsedCount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvitationUpsertOne) UpdateNewValues() *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invitation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invitation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvitationUpsertOne) Ignore() *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvitationUpsertOne) DoNothing() *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvitationCreate.OnConflict
// documentation for more info.
func (u *InvitationUpsertOne) Update(set func(*InvitationUpsert)) *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvitationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvitationUpsertOne) SetUpdatedAt(v time.Time) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateUpdatedAt() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *InvitationUpsertOne) SetDeletedAt(v int) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *InvitationUpsertOne) AddDeletedAt(v int) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateDeletedAt() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *InvitationUpsertOne) SetTokenHash(v string) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateTokenHash() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateTokenHash()
	})
}

// SetProjectID sets the "project_id" field.
func (u *InvitationUpsertOne) SetProjectID(v int) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateProjectID() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateProjectID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *InvitationUpsertOne) SetRoleID(v int) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetRoleID(v)
	})
}

// AddRoleID adds v to the "role_id" field.
func (u *InvitationUpsertOne) AddRoleID(v int) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.AddRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateRoleID() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateRoleID()
	})
}

// ClearRoleID clears the value of the "role_id" field.
func (u *InvitationUpsertOne) ClearRoleID() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.ClearRoleID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *InvitationUpsertOne) SetExpiresAt(v time.Time) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateExpiresAt() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *InvitationUpsertOne) ClearExpiresAt() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.ClearExpiresAt()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *InvitationUpsertOne) SetMaxUses(v int) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *InvitationUpsertOne) AddMaxUses(v int) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateMaxUses() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateMaxUses()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *InvitationUpsertOne) SetUsedCount(v int) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *InvitationUpsertOne) AddUsedCount(v int) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateUsedCount() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateUsedCount()
	})
}

// Exec executes the query.
func (u *InvitationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvitationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvitationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvitationUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvitationUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvitationCreateBulk is the builder for creating many Invitation entities in bulk.
type InvitationCreateBulk struct {
	config
	err      error
	builders []*InvitationCreate
	conflict []sql.ConflictOption
}

// Save creates the Invitation entities in the database.
func (_c *InvitationCreateBulk) Save(ctx context.Context) ([]*Invitation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Invitation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvitationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvitationCreateBulk) SaveX(ctx context.Context) []*Invitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvitationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvitationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invitation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvitationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvitationCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvitationUpsertBulk {
	_c.conflict = opts
	return &InvitationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvitationCreateBulk) OnConflictColumns(columns ...string) *InvitationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvitationUpsertBulk{
		create: _c,
	}
}

// InvitationUpsertBulk is the builder for "upsert"-ing
// a bulk of Invitation nodes.
type InvitationUpsertBulk struct {
	create *InvitationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvitationUpsertBulk) UpdateNewValues() *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invitation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvitationUpsertBulk) Ignore() *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvitationUpsertBulk) DoNothing() *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvitationCreateBulk.OnConflict
// documentation for more info.
func (u *InvitationUpsertBulk) Update(set func(*InvitationUpsert)) *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvitationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvitationUpsertBulk) SetUpdatedAt(v time.Time) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateUpdatedAt() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *InvitationUpsertBulk) SetDeletedAt(v int) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *InvitationUpsertBulk) AddDeletedAt(v int) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateDeletedAt() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *InvitationUpsertBulk) SetTokenHash(v string) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateTokenHash() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateTokenHash()
	})
}

// SetProjectID sets the "project_id" field.
func (u *InvitationUpsertBulk) SetProjectID(v int) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateProjectID() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateProjectID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *InvitationUpsertBulk) SetRoleID(v int) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetRoleID(v)
	})
}

// AddRoleID adds v to the "role_id" field.
func (u *InvitationUpsertBulk) AddRoleID(v int) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.AddRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateRoleID() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateRoleID()
	})
}

// ClearRoleID clears the value of the "role_id" field.
func (u *InvitationUpsertBulk) ClearRoleID() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.ClearRoleID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *InvitationUpsertBulk) SetExpiresAt(v time.Time) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateExpiresAt() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *InvitationUpsertBulk) ClearExpiresAt() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.ClearExpiresAt()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *InvitationUpsertBulk) SetMaxUses(v int) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *InvitationUpsertBulk) AddMaxUses(v int) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateMaxUses() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateMaxUses()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *InvitationUpsertBulk) SetUsedCount(v int) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *InvitationUpsertBulk) AddUsedCount(v int) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateUsedCount() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateUsedCount()
	})
}

// Exec executes the query.
func (u *InvitationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvitationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvitationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvitationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
