// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/invitation"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/project"
)

// InvitationUpdate is the builder for updating Invitation entities.
type InvitationUpdate struct {
	config
	hooks     []Hook
	mutation  *InvitationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the InvitationUpdate builder.
func (_u *InvitationUpdate) Where(ps ...predicate.Invitation) *InvitationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvitationUpdate) SetUpdatedAt(v time.Time) *InvitationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *InvitationUpdate) SetDeletedAt(v int) *InvitationUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableDeletedAt(v *int) *InvitationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *InvitationUpdate) AddDeletedAt(v int) *InvitationUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *InvitationUpdate) SetTokenHash(v string) *InvitationUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableTokenHash(v *string) *InvitationUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *InvitationUpdate) SetProjectID(v int) *InvitationUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableProjectID(v *int) *InvitationUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *InvitationUpdate) SetRoleID(v int) *InvitationUpdate {
	_u.mutation.ResetRoleID()
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableRoleID(v *int) *InvitationUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// AddRoleID adds value to the "role_id" field.
func (_u *InvitationUpdate) AddRoleID(v int) *InvitationUpdate {
	_u.mutation.AddRoleID(v)
	return _u
}

// ClearRoleID clears the value of the "role_id" field.
func (_u *InvitationUpdate) ClearRoleID() *InvitationUpdate {
	_u.mutation.ClearRoleID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InvitationUpdate) SetExpiresAt(v time.Time) *InvitationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableExpiresAt(v *time.Time) *InvitationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *InvitationUpdate) ClearExpiresAt() *InvitationUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *InvitationUpdate) SetMaxUses(v int) *InvitationUpdate {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableMaxUses(v *int) *InvitationUpdate {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *InvitationUpdate) AddMaxUses(v int) *InvitationUpdate {
	_u.mutation.AddMaxUses(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *InvitationUpdate) SetUsedCount(v int) *InvitationUpdate {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableUsedCount(v *int) *InvitationUpdate {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *InvitationUpdate) AddUsedCount(v int) *InvitationUpdate {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *InvitationUpdate) SetProject(v *Project) *InvitationUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the InvitationMutation object of the builder.
func (_u *InvitationUpdate) Mutation() *InvitationMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *InvitationUpdate) ClearProject() *InvitationUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvitationUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvitationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvitationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvitationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvitationUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if invitation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized invitation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := invitation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvitationUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invitation.project"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InvitationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InvitationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InvitationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitation.Table, invitation.Columns, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invitation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(invitation.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(invitation.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(invitation.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(invitation.FieldRoleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoleID(); ok {
		_spec.AddField(invitation.FieldRoleID, field.TypeInt, value)
	}
	if _u.mutation.RoleIDCleared() {
		_spec.ClearField(invitation.FieldRoleID, field.TypeInt)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invitation.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(invitation.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(invitation.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(invitation.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(invitation.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(invitation.FieldUsedCount, field.TypeInt, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.ProjectTable,
			Columns: []string{invitation.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.ProjectTable,
			Columns: []string{invitation.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvitationUpdateOne is the builder for updating a single Invitation entity.
type InvitationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *InvitationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvitationUpdateOne) SetUpdatedAt(v time.Time) *InvitationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *InvitationUpdateOne) SetDeletedAt(v int) *InvitationUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableDeletedAt(v *int) *InvitationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *InvitationUpdateOne) AddDeletedAt(v int) *InvitationUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *InvitationUpdateOne) SetTokenHash(v string) *InvitationUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableTokenHash(v *string) *InvitationUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *InvitationUpdateOne) SetProjectID(v int) *InvitationUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableProjectID(v *int) *InvitationUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *InvitationUpdateOne) SetRoleID(v int) *InvitationUpdateOne {
	_u.mutation.ResetRoleID()
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableRoleID(v *int) *InvitationUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// AddRoleID adds value to the "role_id" field.
func (_u *InvitationUpdateOne) AddRoleID(v int) *InvitationUpdateOne {
	_u.mutation.AddRoleID(v)
	return _u
}

// ClearRoleID clears the value of the "role_id" field.
func (_u *InvitationUpdateOne) ClearRoleID() *InvitationUpdateOne {
	_u.mutation.ClearRoleID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InvitationUpdateOne) SetExpiresAt(v time.Time) *InvitationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableExpiresAt(v *time.Time) *InvitationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *InvitationUpdateOne) ClearExpiresAt() *InvitationUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *InvitationUpdateOne) SetMaxUses(v int) *InvitationUpdateOne {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableMaxUses(v *int) *InvitationUpdateOne {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *InvitationUpdateOne) AddMaxUses(v int) *InvitationUpdateOne {
	_u.mutation.AddMaxUses(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *InvitationUpdateOne) SetUsedCount(v int) *InvitationUpdateOne {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableUsedCount(v *int) *InvitationUpdateOne {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *InvitationUpdateOne) AddUsedCount(v int) *InvitationUpdateOne {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *InvitationUpdateOne) SetProject(v *Project) *InvitationUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the InvitationMutation object of the builder.
func (_u *InvitationUpdateOne) Mutation() *InvitationMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *InvitationUpdateOne) ClearProject() *InvitationUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the InvitationUpdate builder.
func (_u *InvitationUpdateOne) Where(ps ...predicate.Invitation) *InvitationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvitationUpdateOne) Select(field string, fields ...string) *InvitationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Invitation entity.
func (_u *InvitationUpdateOne) Save(ctx context.Context) (*Invitation, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvitationUpdateOne) SaveX(ctx context.Context) *Invitation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvitationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvitationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvitationUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if invitation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized invitation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := invitation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvitationUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invitation.project"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InvitationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InvitationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InvitationUpdateOne) sqlSave(ctx context.Context) (_node *Invitation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitation.Table, invitation.Columns, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invitation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitation.FieldID)
		for _, f := range fields {
			if !invitation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invitation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(invitation.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(invitation.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(invitation.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(invitation.FieldRoleID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRoleID(); ok {
		_spec.AddField(invitation.FieldRoleID, field.TypeInt, value)
	}
	if _u.mutation.RoleIDCleared() {
		_spec.ClearField(invitation.FieldRoleID, field.TypeInt)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invitation.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(invitation.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(invitation.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(invitation.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(invitation.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(invitation.FieldUsedCount, field.TypeInt, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.ProjectTable,
			Columns: []string{invitation.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.ProjectTable,
			Columns: []string{invitation.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Invitation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
