
type UserInfo {
  id: ID!
  email: String!
  firstName: String!
  lastName: String!
  isOwner: Boolean!
  preferLanguage: String!
  avatar: String
  scopes: [String!]!
  roles: [RoleInfo!]!
  projects: [UserProjectInfo!]!
  oidcIdentities: [OIDCIdentityInfo!]!
  hasPassword: Boolean!
}

type OIDCIdentityInfo {
  id: ID!
  idpName: String!
  issuer: String!
  subject: String!
  email: String!
}

type RoleInfo {
  name: String!
}

type UserProjectInfo {
  projectID: ID!
  isOwner: Boolean!
  scopes: [String!]!
  effectiveScopes: [String!]!
  roles: [RoleInfo!]!
}

extend type Query {
    me: UserInfo!
    myProjects: [Project!]!
}

input UpdateMeInput {
  firstName: String
  lastName: String
  preferLanguage: String
  avatar: String
}

extend type Mutation {
    updateMe(input: UpdateMeInput!): User!
    updateMyPassword(input: UpdateMyPasswordInput!): Boolean!
    unlinkOIDCIdentity(id: ID!): Boolean!
}

input UpdateMyPasswordInput {
  oldPassword: String
  newPassword: String!
}
